{% set name = "lantz" %}
{% set version = "0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lantzproject/{{ name }}-core/archive/v{{ version }}.tar.gz
  sha256: bc402b858d3ea245fb56e44b698be477945243de809747f49b99165c48ff0f85

build:
  noarch: python
  number: 0
  entry_points:
    - lantz-config = lantz.core.__main__:config
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - colorama >=0.4.3
    - pimpmyclass
    - pint >=0.15
    - pyqt >=5.12.3
    - pyserial
    - pysignal
    - pyusb
    - pyvisa >=1.10.1
    - pyyaml >=5.3.1
    - qtpy
    - serialize
    - sip
    - stringparser

test:
  imports:
    - lantz
  commands:
    - pip check
    - lantz-config --help
  requires:
    - pip
    - pyvisa-py

about:
  home: https://github.com/lantzproject/lantz
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Simple yet powerful instrumentation in Python

  description: |
    lantz is an automation and instrumentation framework with a clean,
    well-designed and consistent interface. It provides a core of commonly
    used functionalities for building applications that communicate with
    scientific instruments allowing rapid application prototyping,
    development and testing.
  doc_url: https://lantz.readthedocs.io/
  dev_url: https://github.com/lantzproject/lantz

extra:
  recipe-maintainers:
    - mtsolmn
