{% set name = "lantz" %}
{% set version = "0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # lantz
  - url: https://github.com/lantzproject/{{ name }}-core/archive/v{{ version }}.tar.gz
    sha256: bc402b858d3ea245fb56e44b698be477945243de809747f49b99165c48ff0f85
    folder: .
  # lantz-sims
  - url: https://github.com/lantzproject/{{ name }}-sims/archive/v{{ version }}.tar.gz
    sha256: 250a0bd4f6ed2481fcc180dd624646ff4860f2a40aa487bad7ad4255d8589a66
    folder: sims
  # lantz-drivers
  - url: https://github.com/lantzproject/{{ name }}-drivers/archive/v{{ version }}.tar.gz
    sha256: d7e0a3951bdbefcc93bda3b24b1875ae846329ef5386097df4124b78f284b062
    folder: drivers
  # lantz-qt
  - url: https://github.com/lantzproject/{{ name }}-qt/archive/v{{ version }}.tar.gz
    sha256: 97f2a61d888b4682511b757220575ded3ba61cb2d8e641d6276ba8217c3fa7fa
    folder: qt
  # lantz-ino
  - url: https://github.com/lantzproject/{{ name }}-ino/archive/v{{ version }}.tar.gz
    sha256: 228e7fb14d55926c9687e68ef2bb8dd75436599fdc40ee1eb5b333bf5d1254ce
    folder: ino

build:
  noarch: python
  number: 1
  entry_points:
    - lantz = lantz.__main__:main
    - lantz-config = lantz.core.__main__:config
    - lantz-qtdemo = lantz.qt.__main__:main
    - lantz-sims = lantz.sims.__main__:main
    - lantz-ino = lantz.ino.__main__:main
    - 'lantz_subcommands': [
          'config = lantz.core.__main__:config',
          'qtdemo = lantz.qt.__main__:main',
          'sims = lantz.sims.__main__:main',
          'ino = lantz.ino.__main__:main',
      ]
  script:
    - {{ PYTHON }} -m pip install . sims/ drivers/ -vv
    - {{ PYTHON }} -m pip install qt/ -vv
    - {{ PYTHON }} -m pip install ino/ -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - colorama >=0.4.3
    - pimpmyclass
    - pint >=0.15
    - pyqt >=5.12.3
    - pyserial
    - pysignal
    - pyusb
    - pyvisa >=1.10.1
    - pyvisa-py
    - pyyaml >=5.3.1
    - qtpy
    - serialize
    - sip
    - stringparser

test:
  imports:
    - lantz
    - lantz.core
    - lantz.qt
    - lantz.qt.blocks
    - lantz.qt.utils
    - lantz.qt.widgets
    - lantz.sims
    - lantz.drivers
    - lantz.drivers.aa_opto_electronic
    - lantz.ino
    - lantz.ino.templates
  commands:
    - lantz --help
    - lantz-config --help
    - lantz-qtdemo --help
    - lantz-sims --help
    - lantz-ino --help
    - lantz sims fungen tcp --help

about:
  home: https://github.com/lantzproject/lantz
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Simple yet powerful instrumentation in Python'

  description: |
    lantz is an automation and instrumentation framework with a clean,
    well-designed and consistent interface. It provides a core of commonly
    used functionalities for building applications that communicate with
    scientific instruments allowing rapid application prototyping,
    development and testing.
  doc_url: https://lantz.readthedocs.io/
  dev_url: https://github.com/lantzproject/lantz

extra:
  recipe-maintainers:
    - mtsolmn
    - jacobfeder
